#!/usr/bin/env bash
printf "git %s (GIT_SSH_COMMAND=%s)\n" "$*" "${GIT_SSH_COMMAND:-}" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ "$1" == "clone" ]]; then
  mkdir -p "${@: -1}"
  exit "${MOCK_GIT_CLONE_EXIT:-0}"
fi
if [[ "$*" == *"rev-parse --git-dir"* ]]; then
  exit "${MOCK_GIT_REVPARSE_EXIT:-0}"
fi
exit "${MOCK_GIT_EXIT:-0}"
