#!/usr/bin/env bash
printf "hostname %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ "$1" == "-s" ]]; then
  printf "%s\n" "${MOCK_HOSTNAME_OUTPUT:-testhost}"
  exit 0
fi
exec /bin/hostname "$@"
