#!/usr/bin/env bash
printf "mas %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
case "$1" in
  list)
    printf "%s\n" "${MOCK_MAS_LIST_OUTPUT:-}"
    exit 0
    ;;
  *)
    exit "${MOCK_MAS_EXIT:-0}"
    ;;
esac
