#!/usr/bin/env bash
printf "pkgutil %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ -n "${MOCK_PKGUTIL_STDOUT:-}" ]]; then
  printf '%s\n' "${MOCK_PKGUTIL_STDOUT}"
fi
exit "${MOCK_PKGUTIL_EXIT:-1}"
