#!/usr/bin/env bash
printf "snap %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ "${MOCK_SNAP_EXIT:-0}" -ne 0 ]]; then
  exit "${MOCK_SNAP_EXIT}"
fi
case "$1" in
  list) printf "%s\n" "${MOCK_SNAP_LIST_OUTPUT:-}" ;;
esac
exit 0
