#!/usr/bin/env bash
printf "softwareupdate %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
case "$1" in
  -l)
    printf "%s\n" "${MOCK_SOFTWAREUPDATE_LIST_OUTPUT:-}"
    exit 0
    ;;
  *)
    exit "${MOCK_SOFTWAREUPDATE_EXIT:-0}"
    ;;
esac
