#!/usr/bin/env bash
printf "sysctl %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ "$1" == "-n" ]] && [[ "$2" == "machdep.cpu.brand_string" ]]; then
  printf "%s\n" "${MOCK_SYSCTL_CPU:-Apple M1}"
  exit 0
fi
exec /usr/sbin/sysctl "$@"
