#!/usr/bin/env bash
printf "tee %s\n" "$*" >> "${MOCK_CALLS_FILE:-/tmp/mock_calls}"
if [[ "${MOCK_TEE_EXIT:-0}" -ne 0 ]]; then
  cat > /dev/null
  exit "${MOCK_TEE_EXIT}"
fi
/usr/bin/tee "$@" 2>/dev/null || true
