#!/usr/bin/env bash
if [[ -n "${MOCK_UNAME_S}" ]] && [[ "$1" == "-s" ]]; then
  printf "%s\n" "${MOCK_UNAME_S}"
  exit 0
fi
if [[ -n "${MOCK_UNAME_M}" ]] && [[ "$1" == "-m" ]]; then
  printf "%s\n" "${MOCK_UNAME_M}"
  exit 0
fi
exec /usr/bin/uname "$@"
