[appearance]

[appearance.text]
line_height_ratio = 1.2999999523162842
font_name = "Hack"
notebook_font_size = 14.0
font_size = 15.0

[appearance.full_screen_apps]
alt_screen_padding = { custom = { uniform_padding = 0.0 } }

[appearance.vertical_tabs]
enabled = true

[appearance.themes]
theme = { custom = { name = "Green On Black", path = "green_on_black.yaml" } }

[privacy]
crash_reporting_enabled = true
telemetry_enabled = true
custom_secret_regex_list = [
  { name = "IPv4 Address", pattern = '\b((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}\b' },
  {
    name = "IPv6 Address",
    pattern = '\b((([0-9A-Fa-f]{1,4}:){1,6}:)|(([0-9A-Fa-f]{1,4}:){7}))([0-9A-Fa-f]{1,4})\b',
  },
  { name = "Slack App Token", pattern = '\bxapp-[0-9]+-[A-Za-z0-9_]+-[0-9]+-[a-f0-9]+\b' },
  { name = "Phone Number", pattern = '\b(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}[\s.-]\d{4}\b' },
  {
    name = "AWS Access ID",
    pattern = '\b(AKIA|A3T|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{12,}\b',
  },
  {
    name = "MAC Address",
    pattern = '\b((([a-zA-z0-9]{2}[-:]){5}([a-zA-z0-9]{2}))|(([a-zA-z0-9]{2}:){5}([a-zA-z0-9]{2})))\b',
  },
  { name = "Google API Key", pattern = '\bAIza[0-9A-Za-z-_]{35}\b' },
  { name = "Google OAuth ID", pattern = '\b[0-9]+-[0-9A-Za-z_]{32}\.apps\.googleusercontent\.com\b' },
  { name = "GitHub Classic Personal Access Token", pattern = '\bghp_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Fine-Grained Personal Access Token", pattern = '\bgithub_pat_[A-Za-z0-9_]{82}\b' },
  { name = "GitHub OAuth Access Token", pattern = '\bgho_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub User-to-Server Token", pattern = '\bghu_[A-Za-z0-9_]{36}\b' },
  { name = "GitHub Server-to-Server Token", pattern = '\bghs_[A-Za-z0-9_]{36}\b' },
  { name = "Stripe Key", pattern = '\b(?:r|s)k_(test|live)_[0-9a-zA-Z]{24}\b' },
  { name = "Firebase Auth Domain", pattern = '\b([a-z0-9-]){1,30}(\.firebaseapp\.com)\b' },
  { name = "JWT", pattern = '\b(ey[a-zA-z0-9_\-=]{10,}\.){2}[a-zA-z0-9_\-=]{10,}\b' },
  { name = "OpenAI API Key", pattern = '\bsk-[a-zA-Z0-9]{48}\b' },
  { name = "Anthropic API Key", pattern = '\bsk-ant-api\d{0,2}-[a-zA-Z0-9\-]{80,120}\b' },
  { name = "Generic SK API Key", pattern = '\bsk-[a-zA-Z0-9\-]{10,100}\b' },
  { name = "Fireworks API Key", pattern = '\bfw_[a-zA-Z0-9]{24}\b' },
]

[privacy.secret_redaction]
enabled = false

[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]

[agents.warp_agent.input]
nld_in_terminal_enabled = true

[agents.profiles]
agent_mode_execute_readonly_commands = true

[terminal]
osc52_clipboard_access = "write_only"

[terminal.input]
input_box_type_setting = "classic"
alias_expansion_enabled = false
completions_open_while_typing = true
honor_ps1 = true

[code]

[code.indexing]
agent_mode_codebase_context_auto_indexing = true

[account]
is_settings_sync_enabled = true

[general]
default_session_mode = "agent"

[notifications]

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[warpify]

[warpify.ssh]
use_ssh_tmux_wrapper = true
ssh_tmux_deprecation_notice_pending = false
