#!/usr/bin/env bash

usage() {
  printf "Usage: %s <sync|check>\n" "${0}"
}

repo_root() {
  local _script_dir
  _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || return 1
  cd "${_script_dir}/.." && pwd
}

generate_global_rule() {
  local _claude_md _standards_dir _out
  _claude_md="${1}"
  _standards_dir="${2}"
  _out="${3}"

  python3 - "${_claude_md}" "${_standards_dir}" "${_out}" <<'PY'
import pathlib
import sys

claude_path = pathlib.Path(sys.argv[1])
standards_dir = pathlib.Path(sys.argv[2])
out_path = pathlib.Path(sys.argv[3])

if not claude_path.exists():
    sys.exit(f"Missing required file: {claude_path}")

claude_text = claude_path.read_text(encoding="utf-8")

imports = []
for line in claude_text.splitlines():
    if line.startswith("@~/.claude/standards/") and line.endswith(".md"):
        imports.append(line[len("@~/.claude/standards/"):])

if not imports:
    sys.exit(f"No standards imports found in {claude_path}")

sections = []
for name in imports:
    standard_path = standards_dir / name
    if not standard_path.exists():
        sys.exit(f"Missing imported standard: {standard_path}")
    body = standard_path.read_text(encoding="utf-8").rstrip()
    sections.append((name, body))

lines = []
lines.append("---")
lines.append("description: Generated global Cursor rule from CLAUDE.md sources. Do not edit by hand.")
lines.append("alwaysApply: true")
lines.append("---")
lines.append("")
lines.append("# Global Claude standards for Cursor")
lines.append("")
lines.append("This file is generated by `scripts/sync-agent-guidance.sh` from:")
lines.append("")
lines.append("- `CLAUDE.md`")
for name in imports:
    lines.append(f"- `~/.claude/standards/{name}`")
lines.append("")
lines.append("If a repo-level `CLAUDE.md` or `AGENTS.md` is stricter, follow the stricter rule.")
lines.append("")
lines.append("## Imported standards (verbatim)")
lines.append("")
for name, body in sections:
    lines.append(f"### `~/.claude/standards/{name}`")
    lines.append("")
    lines.append(body)
    lines.append("")

out_path.parent.mkdir(parents=True, exist_ok=True)
out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
PY
}

main() {
  local _mode _root _claude_md _standards_dir _target _tmp
  _mode="${1:-}"

  case "${_mode}" in
    sync | check) ;;
    *)
      usage
      return 1
      ;;
  esac

  _root="$(repo_root)" || return 1
  _claude_md="${_OVERRIDE_CLAUDE_MD_PATH:-${_root}/CLAUDE.md}"
  _standards_dir="${_OVERRIDE_STANDARDS_DIR:-${HOME}/.claude/standards}"
  _target="${_OVERRIDE_TARGET_PATH:-${_root}/.cursor/rules/global-claude-standards.mdc}"

  if [[ "${_mode}" == "sync" ]]; then
    generate_global_rule "${_claude_md}" "${_standards_dir}" "${_target}" || return 1
    printf "Updated %s\n" "${_target}"
    return 0
  fi

  _tmp="$(mktemp "${TMPDIR:-/tmp}/global-claude-standards.XXXXXX")" || return 1
  if ! generate_global_rule "${_claude_md}" "${_standards_dir}" "${_tmp}"; then
    rm -f "${_tmp}"
    return 1
  fi

  if [[ -f "${_target}" ]] && cmp -s "${_tmp}" "${_target}"; then
    printf "Agent guidance is in sync\n"
    rm -f "${_tmp}"
    return 0
  fi

  printf "Agent guidance drift detected. Run: make sync-agent-guidance\n"
  rm -f "${_tmp}"
  return 1
}

[[ "${BASH_SOURCE[0]}" != "${0}" ]] && return 0
main "$@"
