#!/usr/bin/env bash

usage() {
  printf "Usage: %s <sync|check>\n" "$0"
}

repo_root() {
  local _script_dir
  _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || return 1
  cd "${_script_dir}/.." && pwd
}

generate_global_rule() {
  local _root _out
  _root="$1"
  _out="$2"

  python3 - "${_root}" "${_out}" <<'PY'
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
out_path = pathlib.Path(sys.argv[2])
claude_path = root / ".claude" / "CLAUDE.md"

if not claude_path.exists():
    raise SystemExit(f"Missing required file: {claude_path}")

claude_text = claude_path.read_text(encoding="utf-8")

comm_match = re.search(
    r"^## Communication Style\s*\n(?P<body>.*?)(?=^## |\Z)",
    claude_text,
    flags=re.M | re.S,
)
communication_body = (comm_match.group("body").strip() if comm_match else "")
communication_lines = [line.rstrip() for line in communication_body.splitlines() if line.strip()]

imports = []
for line in claude_text.splitlines():
    if line.startswith("@~/.claude/standards/") and line.endswith(".md"):
        imports.append(line[len("@~/.claude/"):])

if not imports:
    raise SystemExit("No standards imports found in .claude/CLAUDE.md")

sources = ["CLAUDE.md"] + imports

sections = []
for rel in imports:
    standard_path = root / ".claude" / rel.replace("standards/", "standards/")
    if not standard_path.exists():
        raise SystemExit(f"Missing imported standard: {standard_path}")
    body = standard_path.read_text(encoding="utf-8").rstrip()
    sections.append((rel, body))

lines = []
lines.append("---")
lines.append("description: Generated global Cursor rule from .claude sources. Do not edit by hand.")
lines.append("alwaysApply: true")
lines.append("---")
lines.append("")
lines.append("# Global Claude standards for Cursor")
lines.append("")
lines.append("This file is generated by `scripts/sync-agent-guidance.sh` from:")
lines.append("")
for src in sources:
    lines.append(f"- `.claude/{src}`")
lines.append("")
lines.append("If a repo-level `CLAUDE.md` or `AGENTS.md` is stricter, follow the stricter rule.")
lines.append("")
lines.append("## Communication Style (from `.claude/CLAUDE.md`)")
lines.append("")
if communication_lines:
    lines.extend(communication_lines)
else:
    lines.append("_No communication style section found._")
lines.append("")
lines.append("## Imported standards (verbatim)")
lines.append("")
for rel, body in sections:
    lines.append(f"### `.claude/{rel}`")
    lines.append("")
    lines.append(body)
    lines.append("")

out_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
PY
}

main() {
  local _mode _root _target _tmp
  _mode="${1:-}"
  if [[ -z "${_mode}" ]]; then
    usage
    return 1
  fi

  _root="$(repo_root)" || return 1
  _target="${_root}/.cursor/rules/global-claude-standards.mdc"

  case "${_mode}" in
    sync)
      generate_global_rule "${_root}" "${_target}" || return 1
      printf "Updated %s\n" "${_target}"
      ;;
    check)
      _tmp="$(mktemp "${TMPDIR:-/tmp}/global-claude-standards.XXXXXX")" || return 1
      generate_global_rule "${_root}" "${_tmp}" || { rm -f "${_tmp}"; return 1; }
      if cmp -s "${_tmp}" "${_target}"; then
        printf "Agent guidance is in sync\n"
        rm -f "${_tmp}"
        return 0
      fi
      printf "Agent guidance drift detected. Run: make sync-agent-guidance\n"
      rm -f "${_tmp}"
      return 1
      ;;
    *)
      usage
      return 1
      ;;
  esac
}

main "$@"
