actions:
  - action: command.run
    command: bash
    args:
      - "-c"
      - "RUNZSH=no KEEP_ZSHRC=yes sh -c \"$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)\""
    skip_if_exists: "{{ user.home_dir }}/.oh-my-zsh"

  - action: git.clone
    repo_url: https://github.com/romkatv/powerlevel10k.git
    directory: "{{ user.home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"

  - action: git.clone
    repo_url: https://github.com/tmux-plugins/tpm
    directory: "{{ user.home_dir }}/.tmux/plugins/tpm"
